### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by battaglr** [casualrelaxation/gulp-css-url-adjuster#25]
In the readme:

> Please consider using gulp-rework
> https://github.com/sindresorhus/gulp-rework
> https://github.com/trentearl/gulp-css-url-adjuster/issues/20#issuecomment-109732884

If it is in fact deprecated, would be nice to add a deprecation notice in npm too: https://www.npmjs.com/package/gulp-css-url-adjuster.

Thanks!

**Comment by BigMurry** [comment]
I have maintained a forked version and add some features.
Check here: [gulp-ex-css-url-adjuster](https://github.com/xiaohu-developer/gulp-ex-css-url-adjuster)
